### ISSUE TITLE
Using Flatpak MangoHud for Native App

### ISSUE THREAD

**Issue by Syntist** [flathub/org.freedesktop.Platform.VulkanLayer.MangoHud#11]
Is it possible to use flatpak mangohud for native apps? 
I did find a way to execute mangohud from flatpak directly into terminal, but i think it doesn't have access to access native apps

```
❯ flatpak run org.freedesktop.Platform /usr/lib/extensions/vulkan/MangoHud/bin/mangohud
ERROR: No program supplied

Usage: mangohud <program>
```

Now with the Native app, I'll be using glxgears for demonstration
```
❯ flatpak run org.freedesktop.Platform /usr/lib/extensions/vulkan/MangoHud/bin/mangohud glxgears
env: ‘glxgears’: No such file or directory
```

I wanna use mangohud from flatpak system-wide instead of downloading two version of mangohud. (isn't that the purpose of flatpak, system packaging manager)

**Comment by gasinvein** [comment]
> Is it possible to use flatpak mangohud for native apps?

No. As with other Vulkan layers, MangoHud interacts with the app via ABI, while Flatpak completely isolates app ABI from the host OS.
