### ISSUE TITLE
Support for mangoapp

### ISSUE THREAD

**Issue by VarLad** [flathub/org.freedesktop.Platform.VulkanLayer.MangoHud#12]
Does this flatpak support mangoapp?
If not, can the support be added in this Flatpak? 
Mangoapp is a HUD for gamescope, released with MangoHUD, with more Gamescope specific features

**Comment by VarLad** [comment]
Here's the link to some info https://github.com/flightlessmango/MangoHud/issues/625

**Comment by TheEvilSkeleton** [comment]
I think not. MangoHud requires the `-Dmangoapp=true` build flag, which the flatpak doesn't use. Hey @gasinvein, is it possible if you can add support for it? We need it for https://github.com/bottlesdevs/Bottles/issues/1437.

**Comment by gasinvein** [comment]
@TheEvilSkeleton I have little idea of what mangoapp is. Can you please open a PR?

**Comment by TheEvilSkeleton** [comment]
mangoapp is a MangoHud utility to make MangoHud work with Gamescope.

I'll submit an MR soon.

**Comment by TheEvilSkeleton** [comment]
This can be closed. https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud/pull/14#event-7575424480
