### ISSUE TITLE
App not showing in FlatHub!

### ISSUE THREAD

**Issue by heidiwenger** [flathub/org.freedesktop.Platform.VulkanLayer.MangoHud#16]
"App Not Found

No app with the ID org.freedesktop.Platform.VulkanLayer.MangoHud was found on Flathub. Try searching for the app using the search bar above."

https://flathub.org/apps/details/org.freedesktop.Platform.VulkanLayer.MangoHud

**Comment by heidiwenger** [comment]
The thread about the creation of flatpak was here: https://discourse.flathub.org/t/goverlay-and-mangohud-added-together-in-flatpak-for-very-convenient-use-the-developer-needs-help-on-this/532

**Comment by gasinvein** [comment]
Flathub web frontend doesn't support extensions. flathub/website#53

**Comment by heidiwenger** [comment]
> Flathub web frontend doesn't support extensions. [flathub/website#53](https://github.com/flathub/website/issues/53)

Oh. Well out of curiosity; would a snap / Snap Store support extension then?

**Comment by gasinvein** [comment]
I have no idea if Snap has a concept similar to Flatpak extension.

Why do you even care about Flathub website not showing extensions? The website is purely informational and isn't involved in installing flatpaks anyhow.

**Comment by heidiwenger** [comment]
> I have no idea if Snap has a concept similar to Flatpak extension.
> 
> Why do you even care about Flathub website not showing extensions? The website is purely informational and isn't involved in installing flatpaks anyhow.

I thought this is MangoHud the software. Oh.
