### ISSUE TITLE
MangoHud stopped working after runtime update

### ISSUE THREAD

**Issue by Monstanner** [flathub/org.freedesktop.Platform.VulkanLayer.MangoHud#17]
Mangohud no longer works for me. Mangohud no longer works for me. The Normal Mangohud (AUR) works, but as soon as I start a Steam (Flatpak) game, the game does not start and console says the following: `/bin/sh: line 1: mangohud: command not found.`As a start option I use: `mangohud %command%`. `Mangohud=1` does not work. The game starts, but the hud is not there.

**Comment by gasinvein** [comment]
Steam has recently updated to a newer runtime, probably you need to install mangohud flatpak extension matching the runtime. Try running `flatpak install org.freedesktop.Platform.VulkanLayer.MangoHud//22.08`

**Comment by Monstanner** [comment]
> Steam has recently updated to a newer runtime, probably you need to install mangohud flatpak extension matching the runtime. Try running `flatpak install org.freedesktop.Platform.VulkanLayer.MangoHud//22.08`

Now it works again. Thanks for the quick help.

**Comment by soredake** [comment]
Probably related: https://github.com/flatpak/flatpak/issues/4208

**Comment by jobukkit** [comment]
Had this problem too, now the correct version is `flatpak install org.freedesktop.Platform.VulkanLayer.MangoHud//23.08`.
