### ISSUE TITLE
Where to put configuration file?

### ISSUE THREAD

**Issue by poperigby** [flathub/org.freedesktop.Platform.VulkanLayer.MangoHud#27]
I have my configuration file in `~/.var/app/com.valvesoftware.Steam/config/MangoHud` but it doesn't apply to application besides Steam, even though MangoHud does show up in other Vulkan applications.

**Comment by gasinvein** [comment]
You can put it in `~/.config/MangoHud` and have Steam flatpak (and other flatpaks you need to work with MangoHud) have acess to `xdg-config/MangoHud`

**Comment by Perkolator** [comment]
> You can put it in `~/.config/MangoHud` and have Steam flatpak (and other flatpaks you need to work with MangoHud) have acess to `xdg-config/MangoHud`

Doesn't work with Bottles. It won't read from `~/.config/MangoHud` although given Flatpak override.
