### ISSUE TITLE
Multiple rows of the same output?

### ISSUE THREAD

**Issue by Aegeontis** [flathub/org.freedesktop.Platform.VulkanLayer.MangoHud#29]
Hey, I am using a lutris flatpak and the flatpak version of mangohud (22.08). In lutris I enabled the `FPS counter (MangoHud)` option and added `MANGOHUD_CONFIG=fps_only,background_alpha=0`. The result is the following ingame:
![image](https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud/assets/140899260/82d5f28d-acfc-4b66-ba9e-7e8949d1b321)

I tested a game with steam (also flatpak version) and I get the same issue.

GPU: Nvidia rtx3070
Driver version: 535.98
OS: Fedora 38 (silverblue)

**Comment by flightlessmango** [comment]
This is bug in mangohud and not in the flatpak, report it there instead [MangoHud](https://github.com/flightlessmango/MangoHud/issues)
