### ISSUE TITLE
Don't work after steam update to org.freedesktop.Platform 23.08.0

### ISSUE THREAD

**Issue by TrixieUA** [flathub/org.freedesktop.Platform.VulkanLayer.MangoHud#32]
I have org.freedesktop.Platform.VulkanLayer.MangoHud 23.08 but it doent work.

**Comment by okseb** [comment]
Duplicate issue see [here](https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud/issues/31) & [here](https://github.com/ValveSoftware/steam-runtime/issues/618) for trackers

**Comment by TrixieUA** [comment]
I found [this issue](https://github.com/flightlessmango/MangoHud/issues/1084) in [MangoHud](https://github.com/flightlessmango/MangoHud) and it seems to be related, down at the bottom there was [this patch](https://github.com/flightlessmango/MangoHud/commit/5754ca13ee2cdf19a76b4fc79dd914a58d6371f5)  and i applied it to flatpak wersion of MangoHud and it works again! Maybe there is a way to get this patch into 23.08 version of MangoHud flatpak?

**Comment by ghost** [comment]
Thanks @TrixieUA, excellent find. This resolves the problem on my systems as well. I've submitted #33

**Comment by ohno1052** [comment]
@TrixieUA 💀

**Comment by okseb** [comment]
Not sure if anyone wants to test it or if it's worthwhile but this patch should no longer be necessary as per https://github.com/ValveSoftware/steam-runtime/issues/618#issuecomment-1728334026
