### ISSUE TITLE
GPU Percentage for AMD iGPUs is broken in the 0.6.7 version

### ISSUE THREAD

**Issue by VarLad** [flathub/org.freedesktop.Platform.VulkanLayer.MangoHud#9]
@gasinvein GPU Percentage for AMD iGPUs is broken in the 0.6.7 version (which has been removed from [Releases](https://github.com/flightlessmango/MangoHud/releases) apparently)
 Fix is, either temporarily revert to https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud/commit/a6b9b6b0fdfa5154caa6d396136a71246ccf0189 commit
 or update the source to https://github.com/flightlessmango/MangoHud/commit/b30302c889eed2d01744411233a041a0491cfba9

**Comment by gasinvein** [comment]
Thanks. Reverted. Let's wait for the next release.
